### ISSUE TITLE
dnswarden is down in past few hours

### ISSUE THREAD

**Issue by gloschtla** [bhanupratapys/dnswarden#16]
in Android 9 "private DNS mode" ...dot.dnswarden.com always worked before. But today it suddenly says "Couldn't connect". Also the customized DNS server in my router's settings made all the devices offline, today.

**Comment by bhanupratapys** [comment]
Hello, plaintext dns issue should be fixed now. According to my monitoring logs, DoT/DoH was never down. The valid domains for non-ecs DoT are `adblock-dot.dnswarden.com` , `uncensored-dot.dnswarden.com` and `adult-filter-dot.dnswarden.com`.

For ecs support , `ecs-adblock-dot.dnswarden.com` , `ecs-adult-filter-dot.dnswarden.com` and `ecs-uncensored-dot.dnswarden.com`. 

If you are located in and around the server region then stick with non-ecs DoT domains. 

Also DoT will **only** work on default port 853 from now on.

**Comment by gloschtla** [comment]
I wonder what happened. The router works again, as before: with 116.203.70.156 and the other 3 normal DNS addresses of dnswarden. Only Android still doesnt work in private DNS mode, but it always worked before, and nothing was changed.

**Comment by bhanupratapys** [comment]
The router issue which you had is totally my fault, are you still having the problem on android ?

**Comment by bhanupratapys** [comment]
Closing this, everything is functioning normally after the server upgrade.

In case you find any unusual behaviour, either reopen this issue or a new one.
